const lines={
 manitowoc:{name:'Manitowoc Ice',desc:'Ice production, storage, dispensing, condenser selection and application sizing.',facts:[
  ['Production vs. storage','Treat daily ice production and immediately available stored ice as separate sizing problems.'],
  ['Indigo NXT','Modular cuber platform. Verify cube type, condenser, voltage, bin/dispenser compatibility and published performance at application conditions.'],
  ['CNF0201 / CNF0202','Countertop nugget ice maker/dispensers. Current literature lists 315 lb/day at 70°F/50°F and 222 lb/day at 90°F/70°F; 0201 and 0202 differ in storage/height.'],
  ['Application rule','The right machine is not the right machine if it does not fit. Verify installed dimensions, clearances and delivery path.'] ],
  refs:[['CNF0201 / CNF0202 spec','https://www.manitowocice.com/asset/?id=irurh&prefLang=en&regions=us']]
 },
 franke:{name:'Franke Coffee Systems',desc:'Bean-to-cup platforms, beverage programs, peak throughput, water quality and modular options.',facts:[
  ['A400 Fresh Brew','Two bean hoppers with dedicated grinders; current U.S. spec lists 13.4 W × 33.5 H × 23.6 D and 208V/30A.'],
  ['A1000 FLEX','Combines espresso-based beverages and fresh-brewed coffee; current Franke literature lists up to 300 cups/day and up to six flavors.'],
  ['Peak throughput','Daily cup rating is not the same as acceptable queue performance during a concentrated rush.'],
  ['Water quality','Treat site water testing and appropriate treatment as part of the equipment specification and reliability plan.'] ],
  refs:[['Franke product literature','https://www.franke.com/us/en/coffee-systems/resources/brochures-leaflets.html'],['A400 Fresh Brew','https://www.franke.com/us/en/coffee-systems/products/fully-automatic-coffee-machines/a400-fresh-brew-coffee-machine.html'],['A1000 FLEX','https://www.franke.com/us/en/coffee-systems/products/fully-automatic-coffee-machines/a1000-flex-coffee-machine.html']]
 }
};
const scenarios={
 manitowoc:{title:'Restaurant Ice System',opening:'Dealer: I have a 150-seat full-service restaurant replacing an older ice machine. The owner says his friend has a 900-pound Manitowoc and wants the same thing. Can you quote it?',facts:{utility:'208–230V single-phase is available, along with water and a floor drain.',location:'The machine is in a back-of-house utility room that reaches about 80–85°F in summer. Incoming water is about 65°F.',dimension:'The room is 8 × 10 feet with a 9-foot ceiling. There are 48 inches of usable wall width and a 36-inch doorway with a straight approach.',existing:'The existing unit is an approximately 14-year-old 600-class Manitowoc on roughly a 400-pound bin. Service notes say it is scaled and underperforming.',demand:'The bin is generally full around 4 PM. Friday/Saturday dinner is the peak; they currently buy roughly five to eight 20-pound bags on a busy night.',ice:'They currently use half-dice and want to keep half-dice.',use:'Ice serves the full bar, three bar wells, fountain drinks, iced tea, water service and some kitchen prep. No seafood displays or large cooler filling.'},required:['utility','location','dimension','existing','demand','ice','use'],solution:'A defensible recommendation should be based on verified actual demand, equipment condition, production at site conditions, storage, fit and utilities—not the owner’s comparison to another restaurant.'},
 franke:{title:'Convenience Store Coffee Program',opening:'Dealer: New convenience store. The owner wants an A600 and expects about 250 coffee beverages per day. They want regular coffee, espresso drinks, cappuccinos, lattes and iced coffee. Can you price it?',facts:{menu:'They want 12, 16 and 20 oz drinks; regular and decaf coffee, espresso, cappuccino, latte and iced beverages.',mix:'Morning mix is estimated at 60% fresh-brew coffee, 30% milk-based espresso drinks and 10% espresso/Americano. Later demand shifts toward specialty and iced beverages.',peak:'About 120–140 of the projected 250 daily drinks occur between 5:30 and 9:00 AM. The owner considers a six-person line unacceptable.',milk:'They want whole milk and oat milk.',flavor:'They want vanilla, caramel, hazelnut and mocha initially, with room to expand.',utility:'This is new construction. 208V power, water and drains can be provided as required.',space:'The original counter allocation is 48 inches wide and 30 inches deep, but the architect can revise it because the project is still in design.',service:'The program will be fully self-service and is intended to be a traffic driver.'},required:['menu','mix','peak','milk','flavor','utility','space','service'],solution:'A strong recommendation must address beverage capability, peak queue throughput, redundancy, physical space, utilities, water treatment and the operator’s business objectives. Multiple architectures may be defensible.'}
};
let current=null,found=new Set(),messages=[];
function home(){current=null;document.querySelector('#app').innerHTML=`<section class=hero><div class=eyebrow>Internal Training Prototype</div><h1>Don Stevens Training Center</h1><p class=sub>Build manufacturer knowledge, strengthen application discovery and practice defensible equipment recommendations.</p></section><h2>Select a product line</h2><div class=grid>${Object.entries(lines).map(([k,v])=>`<div class='card click' onclick="line('${k}')"><span class=tag>Product line</span><h3>${v.name}</h3><p>${v.desc}</p></div>`).join('')}</div>`}
function line(k){current=k;let v=lines[k];document.querySelector('#app').innerHTML=`<div class=back onclick=home()>← Product lines</div><section class=hero><div class=eyebrow>Product Line</div><h1>${v.name}</h1><p class=sub>${v.desc}</p></section><div class=grid><div class='card click' onclick="quick('${k}')"><h3>Quick Facts & References</h3><p>Field-ready specifications, application reminders and current source links.</p></div><div class='card click' onclick="study('${k}')"><h3>Study Up</h3><p>Review key concepts and test recall with short knowledge checks.</p></div><div class='card click' onclick="scenario('${k}')"><h3>Scenario Training</h3><p>Work an incomplete dealer lead, discover the application and defend a recommendation.</p></div></div>`}
function quick(k){let v=lines[k];document.querySelector('#app').innerHTML=`<div class=back onclick="line('${k}')">← ${v.name}</div><h1>Quick Facts & References</h1><div class=facts>${v.facts.map(x=>`<div class=fact><div class=label>${x[0]}</div><b>${x[1]}</b></div>`).join('')}</div><h2>Current manufacturer sources</h2><div class=card>${v.refs.map(r=>`<p><a href='${r[1]}' target=_blank rel=noopener>${r[0]} ↗</a></p>`).join('')}<div class=source>Manufacturer documentation is the source of truth. Verify specifications and compatibility before quotation or order placement.</div></div>`}
function study(k){let v=lines[k];let qs=k==='manitowoc'?[['Why can a larger bin not correct inadequate daily production?','Because storage changes the reserve available at a moment in time; it does not increase the machine’s ice-making rate.'],['What must be checked in addition to final equipment dimensions?','Required operating clearances and the complete delivery/access path.']]:[['Why is cups/day alone insufficient for a self-service coffee program?','A concentrated peak can create unacceptable queues even when total daily volume is within the machine’s published range.'],['Why verify water quality?','Water affects beverage quality, scale formation, reliability and the treatment/filtration specification.']];document.querySelector('#app').innerHTML=`<div class=back onclick="line('${k}')">← ${v.name}</div><h1>Study Up</h1><p class=sub>Click each knowledge check to reveal the answer.</p><div class=grid>${qs.map((q,i)=>`<div class='card click' onclick="this.querySelector('p').hidden=false"><div class=label>Knowledge check ${i+1}</div><h3>${q[0]}</h3><p hidden>${q[1]}</p></div>`).join('')}</div>`}
function scenario(k){current=k;found=new Set();messages=[];let s=scenarios[k];messages.push(['dealer',s.opening]);renderScenario()}
function renderScenario(){let s=scenarios[current];let pct=Math.round(found.size/s.required.length*100);document.querySelector('#app').innerHTML=`<div class=back onclick="line('${current}')">← ${lines[current].name}</div><h1>${s.title}</h1><div class=scenario><div><div class=chat id=chat>${messages.map(m=>`<div class='msg ${m[0]}'>${esc(m[1])}</div>`).join('')}</div><div class=inputrow><textarea id=q placeholder='Ask the dealer a discovery question or explain your recommendation...'></textarea><button class=btn onclick=ask()>Send</button></div></div><aside class=card><div class=label>Discovery progress</div><h2>${pct}%</h2><div class=meter><i style='width:${pct}%'></i></div><p>${found.size} of ${s.required.length} core discovery areas surfaced.</p><button class='btn alt' onclick=teach()>I’m stuck — coach me</button><p><button class='btn alt' onclick=finish()>Review scenario</button></p><div class=source>Progress measures discovery coverage, not whether one predetermined SKU has been guessed.</div></aside></div>`;let c=document.querySelector('#chat');c.scrollTop=c.scrollHeight}
function ask(){let q=document.querySelector('#q').value.trim();if(!q)return;messages.push(['trainee',q]);let s=scenarios[current],t=q.toLowerCase(),hits=[];const map={utility:['power','voltage','electric','utility','water line','drain','amp'],location:['where','location','ambient','temperature','room'],dimension:['dimension','size','space','width','height','door','clearance','fit'],existing:['existing','current','old','service','condition','model'],demand:['demand','peak','busy','bag','run out','usage','use per'],ice:['ice type','cube','dice','half'],use:['using','used for','application','bar','kitchen'],menu:['menu','drink','size','beverage'],mix:['mix','espresso vs','fresh brew','percentage'],peak:['peak','rush','hour','line','queue'],milk:['milk','dairy','oat'],flavor:['flavor','syrup'],space:['counter','space','dimension','width','depth','fit'],service:['self service','self-service','staff','customer','traffic']};for(const [key,words] of Object.entries(map)){if(s.facts[key]&&words.some(w=>t.includes(w))){found.add(key);hits.push(s.facts[key])}}if(hits.length)messages.push(['dealer',hits.join(' ')]);else if(/recommend|quote|i think|i would|suggest|spec|model/.test(t))messages.push(['dealer',found.size<s.required.length?'I can work with that direction, but there are still application details you have not established. What else would you want to verify before releasing the quote?':'That is a defensible direction. Explain the application reasoning and any items you would still verify in current manufacturer documentation before ordering.']);else messages.push(['dealer','I do not have additional information on that point in this scenario. Try approaching the application from another discovery angle.']);renderScenario()}
function teach(){let s=scenarios[current],miss=s.required.find(x=>!found.has(x));if(!miss){messages.push(['dealer','You have surfaced all core discovery areas. Move to your recommendation and explain why it fits the application.'])}else{let hints={utility:'Consider what the building can actually supply to the equipment.',location:'Consider the operating environment, not only the customer’s desired capacity.',dimension:'Consider both the final equipment location and how the equipment gets there.',existing:'The existing equipment may provide useful evidence—but only if you understand its condition.',demand:'Separate average daily volume from concentrated peak demand.',ice:'Confirm the product/output format the operation actually wants.',use:'Ask what the product is actually being used to accomplish.',menu:'Build the beverage menu before building the machine.',mix:'The proportion of simple versus complex beverages changes the workload.',peak:'Daily capacity does not describe queue performance.',milk:'Milk type and quantity can materially change the configuration.',flavor:'Flavor requirements affect the accessory configuration.',space:'A technically correct system still has to fit and be usable.',service:'Understand who operates the equipment and what experience the customer expects.'};messages.push(['dealer','Coaching note: '+hints[miss]])}renderScenario()}
function finish(){let s=scenarios[current],missing=s.required.filter(x=>!found.has(x));document.querySelector('#app').innerHTML=`<div class=back onclick="scenario('${current}')">← Restart scenario</div><h1>Scenario Review</h1><div class=grid><div class=card><div class=label>Discovery</div><h2>${Math.round(found.size/s.required.length*100)}%</h2><p>${found.size} of ${s.required.length} core areas surfaced.</p></div><div class=card><div class=label>Coaching summary</div><p>${s.solution}</p></div></div><div class=card><h3>Areas not yet surfaced</h3><p>${missing.length?missing.map(x=>x[0].toUpperCase()+x.slice(1)).join(' • '):'None — all core discovery areas were addressed.'}</p><div class=source>This prototype evaluates discovery coverage. Future versions can add richer recommendation scoring and scenario branches.</div></div>`}
function esc(s){return s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}home();
